In [19]:
import pandas as pd
import numpy as np

#### First warm-up questions (basic Pandas)

1. Load the CSV file into a pandas DataFrame.
2. Show the first 10 rows of the dataset.
3. Display the shape of the dataset.
4. Show all column names.
5. Get a summary of statistics for numeric columns.
6. Check how many missing values exist in each column.
7. Display the data types of all columns.

---

In [6]:
df = pd.read_csv('top_manhwas_acc_to_chatgpt.csv')
df.head(10)

                       name          author            genre  year
0                   Lookism   Park Tae-Joon  School / Action  2014
1  Viral Hit (How to Fight)   Park Tae-Joon  Street Fighting  2019
2                 Weak Hero         Seopass  School / Action  2018
3                 The Boxer     Jung Ji-Hun  Boxing / Sports  2019
4        God of High School     Yongje Park     Martial Arts  2011
5               Study Group  Hyungwook Shin  School / Action  2019
6                Hanlim Gym        Hyeseong  School / Action  2020
7               Manager Kim   Park Tae-Joon     Martial Arts  2021
8                To Not Die           Parae  Street Fighting  2021
9           Quest Supremacy   Park Tae-Joon  School / Action  2022

In [38]:
df2 = pd.read_csv('students.csv')

In [7]:
df.shape

(25, 4)

In [15]:
columns = df.columns
columns

Index(['name', 'author', 'genre', 'year'], dtype='str')

In [ ]:
df['year'].describe().dtypes in ['int','float']

True

In [31]:
# for doing describe of all , numeric columns 
#  we first need to extract the numeric columns
# df[columns].dtypes==int

# A modern approach 
a = df.select_dtypes(include='number')
print(a.columns)
a.describe()

Index(['year'], dtype='str')

              year
count    25.000000
mean   2019.160000
std       2.764055
min    2011.000000
25%    2019.000000
50%    2020.000000
75%    2021.000000
max    2023.000000

In [33]:
df.isnull().sum()

name      0
author    0
genre     0
year      0
dtype: int64

In [ ]:
df.dtypes

name        str
author      str
genre       str
year      int64
dtype: object

In [39]:
df2[['name','marks']].head()

    name  marks
0  Aisha     88
1  Rahul     75
2   Neha     92
3  Arjun     68
4  Priya     85

In [43]:
# : selects all columns but , not using it would also select all columns
# I used it kyuki I wanted to show how to show select columns
df2.loc[df2['marks']>80,:].head() 

# An easier alternative
df2.query('marks > 80').head()

   student_id   name  age        department  marks       city
0         101  Aisha   20  Computer Science     88      Delhi
2         103   Neha   19       Electronics     92  Bangalore
4         105  Priya   20  Information Tech     85       Pune
6         107  Meera   20        Mechanical     91     Jaipur

In [45]:
df2.query('city == "Delhi"')

   student_id   name  age        department  marks   city
0         101  Aisha   20  Computer Science     88  Delhi
5         106  Karan   21  Computer Science     79  Delhi

In [49]:
df2.query('marks > 59 and marks < 81')
df2.loc[(df2['marks']>=60) & (df2['marks']<=80)]

   student_id   name  age        department  marks       city
1         102  Rahul   21        Mechanical     75     Mumbai
3         104  Arjun   22             Civil     68    Chennai
5         106  Karan   21  Computer Science     79      Delhi
7         108  Rohan   22       Electronics     73  Hyderabad

In [54]:
df2.loc[(df2['marks']>75) & (df2['city']=='Delhi')]

   student_id   name  age        department  marks   city
0         101  Aisha   20  Computer Science     88  Delhi
5         106  Karan   21  Computer Science     79  Delhi

In [56]:
a = df2.sort_values(by='marks',ascending=False)
a

   student_id   name  age        department  marks       city
2         103   Neha   19       Electronics     92  Bangalore
6         107  Meera   20        Mechanical     91     Jaipur
0         101  Aisha   20  Computer Science     88      Delhi
4         105  Priya   20  Information Tech     85       Pune
5         106  Karan   21  Computer Science     79      Delhi
1         102  Rahul   21        Mechanical     75     Mumbai
7         108  Rohan   22       Electronics     73  Hyderabad
3         104  Arjun   22             Civil     68    Chennai

In [60]:
df2.loc[a[:5].index,'name']

2     Neha
6    Meera
0    Aisha
4    Priya
5    Karan
Name: name, dtype: str

In [66]:
df2['pass_status'] = np.where(df2['marks']>=40,'Pass','Fail')

In [67]:
df2

   student_id   name  age        department  marks       city pass_status
0         101  Aisha   20  Computer Science     88      Delhi        Pass
1         102  Rahul   21        Mechanical     75     Mumbai        Pass
2         103   Neha   19       Electronics     92  Bangalore        Pass
3         104  Arjun   22             Civil     68    Chennai        Pass
4         105  Priya   20  Information Tech     85       Pune        Pass
5         106  Karan   21  Computer Science     79      Delhi        Pass
6         107  Meera   20        Mechanical     91     Jaipur        Pass
7         108  Rohan   22       Electronics     73  Hyderabad        Pass

In [72]:
df2['marks'] += 5

In [74]:
df2.rename({'marks':'exam_marks'},axis=1)

   student_id   name  age        department  exam_marks       city pass_status
0         101  Aisha   20  Computer Science          93      Delhi        Pass
1         102  Rahul   21        Mechanical          80     Mumbai        Pass
2         103   Neha   19       Electronics          97  Bangalore        Pass
3         104  Arjun   22             Civil          73    Chennai        Pass
4         105  Priya   20  Information Tech          90       Pune        Pass
5         106  Karan   21  Computer Science          84      Delhi        Pass
6         107  Meera   20        Mechanical          96     Jaipur        Pass
7         108  Rohan   22       Electronics          78  Hyderabad        Pass

In [75]:
df2.drop('city',axis=1)

   student_id   name  age        department  marks pass_status
0         101  Aisha   20  Computer Science     93        Pass
1         102  Rahul   21        Mechanical     80        Pass
2         103   Neha   19       Electronics     97        Pass
3         104  Arjun   22             Civil     73        Pass
4         105  Priya   20  Information Tech     90        Pass
5         106  Karan   21  Computer Science     84        Pass
6         107  Meera   20        Mechanical     96        Pass
7         108  Rohan   22       Electronics     78        Pass

In [77]:
df2['marks'].fillna(np.mean(df2['marks']))

0    93
1    80
2    97
3    73
4    90
5    84
6    96
7    78
Name: marks, dtype: int64

In [83]:
print(df2.groupby("department")['marks'].mean())

department
Civil               73.0
Computer Science    88.5
Electronics         87.5
Information Tech    90.0
Mechanical          88.0
Name: marks, dtype: float64

In [99]:
df2.groupby('department').size()

department
Civil               1
Computer Science    2
Electronics         2
Information Tech    1
Mechanical          2
dtype: int64

In [100]:
df2.groupby('department')['marks'].max()

department
Civil               73
Computer Science    93
Electronics         97
Information Tech    90
Mechanical          96
Name: marks, dtype: int64

In [111]:
df2.groupby('city')['marks'].mean()

city
Bangalore    97.0
Chennai      73.0
Delhi        88.5
Hyderabad    78.0
Jaipur       96.0
Mumbai       80.0
Pune         90.0
Name: marks, dtype: float64

In [114]:
df2.groupby('department')['marks'].mean()

department
Civil               73.0
Computer Science    88.5
Electronics         87.5
Information Tech    90.0
Mechanical          88.0
Name: marks, dtype: float64

In [115]:
df2.groupby('department')['marks'].mean().idxmax()

'Information Tech'

In [117]:
df2.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
dtype: bool

In [118]:
df2.drop_duplicates('student_id')

   student_id   name  age        department  marks       city pass_status
0         101  Aisha   20  Computer Science     93      Delhi        Pass
1         102  Rahul   21        Mechanical     80     Mumbai        Pass
2         103   Neha   19       Electronics     97  Bangalore        Pass
3         104  Arjun   22             Civil     73    Chennai        Pass
4         105  Priya   20  Information Tech     90       Pune        Pass
5         106  Karan   21  Computer Science     84      Delhi        Pass
6         107  Meera   20        Mechanical     96     Jaipur        Pass
7         108  Rohan   22       Electronics     78  Hyderabad        Pass